### ISSUE TITLE
Argo workflow plugin for task runner

### ISSUE THREAD

**Issue by joshliberty** [Project-MONAI/monai-deploy-workflow-manager#54]
Including a wrapped MAP

**Comment by mocsharp** [comment]
## Argo Task Plug-in

The Argo task plug-in provides integration with Argo Workflow and requires Argo with version `3.3.3` or higher.

### Assumptions

* A `kind:WorkflowTemplate` is deployed on the targeted Argo server with API endpoints available to submit workflow and get workflow statuses.

### Requirements

The plug-in handles any `md.tasks.dispatch` event with the `task_assembly_name` set to `Monai.Deploy.WorkflowManager.TaskManager.Argo.ArgoPlugin, Monai.Deploy.WorkflowManager.TaskManager.Argo` with the following arguments defined in the `task_plugin_arguments`:

- `baseUrl`: URL to the Argo RESTful API
- `workflow template name`: The deployed `kind: WorkflowTempalte` that contains the actual workflow
- `workflowTemplateEntrypoint`: is the `entrypoint` of the actual workflow
- `messagingEndpoint`: The endpoint of the messaging broker where the callback message is published to. E.g. 2.2.3.4/virtualHost
- `messagingUsername`: Username to authenticate and publish the callback message.
- `messagingPassword`: Password to authenticate and publish the callback message.
- `messagingTopic`: Topic or routing key, e.g. `md.tasks.callback`.
- `messagingExchange`:  The exchange where the message is sent to.
- (optional) `namespace`: Argo or kubernetes namespace where the template is deployed as well as where the job will be submitted. If not provided, defaults to `default`.
- (optional) `timeoutSeconds`: the `ActiveDeadlineSeconds` of the Argo workflow.
- (optional) `apiToken`: the token used to authenticate to the Argo server.

### Argo Workflow

At the time of writing, Argo does not support referencing a `kind:WorkflowTemplate` with output artifact mappings.  Therefore, the plug-in build a `kind:Workflow` (hereafter, _job template_) by reading the `kind:WorkflowTemplate` defined in `workflowTemplateName` and copies the template defined in the `workflowTemplateEntrypoint` into the _job template_.

The plug-in would also copy, recursively, any steps or dags defined in the `workflowTemplateEntrypoint`.

### Artifact Binding

Any input or output artifacts defined in any `template` copied to the _job template_ require a matching input or output `Storage` object defined in the `md.tasks.dispatch` event.  If a matching (by name, case-sensitive)  storage mapping cannot be found, the plug-in would fail with `FailureReason.PluginError`.  

#### Credentials

Credentials to access the input and output artifact storage are generated and managed by the Workflow Manager.  
The plug-in takes the access key & access secret pair to generate `Kubernetes secrets`.  The plug-in deletes the secrets upon disposal of the plugin instance.

### End Hook

The plug-in also injects an `end-hook` into the _job template_ so when the Argo workflow completes, a `md.tasks.callback` event is emitted to the message broker.

**Comment by joshliberty** [comment]
@mocsharp two notes:

1. I don't think we need to be so strict with output artefacts. I wouldn't want the workflow to have to explicitly define all files generated by any of the steps in an Argo workflow. It'll be extremely verbose and something that the workflow creator at the hospital shouldn't need to worry about. In other words, I'm happy to do that validation for the initial input artefacts for the entrypoint template, but not for output artefacts and definitely not for intermediary artefacts.
2. Does it really make sense for the messaging engine credentials to be sent in the task dispatch event? I think it should be stored in the task executer configuration file. The communication between Argo and the task manager will not involve the workflow manager for ever, so they may choose to use messaging engine that the workflow manager knows nothing about.

**Comment by mocsharp** [comment]
1. We are not requiring the workflow to explicitly define all files but rather just tell us if they need to output anything. 
   E.g with the following workflow definition, we will create 3 output artifact mappings for them.
```
"output": [ "fracture_report", "dicom_sr", "ehr" ]
```

For, Argo plugin, we would expect an Argo template with some output artifact mapping with names: `fracture_report`, `dicom_sr` and `ehr`.

```
... 
kind: WorkflowTemplate
metadata:
  name: some-template
spec:
  entrypoint: preprocessing
  templates:
    - name: preprocessing
      ...
      outputs:
        artifacts:
        - name: dicom_sr # userdefined
          path: /dicom_sr/ # userdefined
          s3: #injected by the plugin
            endpoint: 10.20.30.40
                bucket: monaideploy
                key: "/somepath/dicom_sr"
                insecure: true 
                accessKeySecret:
                  name: my-s3-credentials
                  key: accessKey
                secretKeySecret:
                  name: my-s3-credentials
                  key: secretKey
    - name: postprocessing
      ...
      outputs:
        artifacts:
        - name: dicom_sr # userdefined
          path: /dicom_sr/ # userdefined
          s3: #injected by the plugin
            endpoint: 10.20.30.40
                bucket: monaideploy
                key: "/somepath/dicom_sr"
                insecure: true 
                accessKeySecret:
                  name: my-s3-credentials
                  key: accessKey
                secretKeySecret:
                  name: my-s3-credentials
                  key: secretKey
        - name: ehr # userdefined
          path: /dicom_sr/ # userdefined
          s3: #injected by the plugin
            endpoint: 10.20.30.40
                bucket: monaideploy
                key: "/somepath/ehr"
                insecure: true 
                accessKeySecret:
                  name: my-s3-credentials
                  key: accessKey
                secretKeySecret:
                  name: my-s3-credentials
                  key: secretKey
```

Note: there is a separate discussion about intermediary artifact storage. What we define above are known output artifacts from an Argo workflow.

I think the application developer releases a model (MAP, Argo Workflow) they must include, in their documentation or some other form, the expected input, and output; where they are reading data from as well as where they are writing results to.  With that, the person composing MD Workflow would know exactly what to expect.

With the assumption in the previous paragraph and the same workflow definition.  If a person is using the HTTP plugin, he/she must know that the HTTP endpoint(s) would have 3 different types of outputs and we can expect the HTTP plugin to write the 3 different data types into 3 different artifact mappings:

```
"output": [ "fracture_report", "dicom_sr", "ehr" ]
```


2. Yes, given that Task Manager also has credentials for the messaging service, the Task Manager could make them available to the plugins.
